#!/bin/sh
# buildsc: Build statically linked ShellCheck
cabal update &&
cabal install --dependencies-only &&
cabal build Paths_ShellCheck &&
ghc -optl-static -optl-pthread -idist/build/autogen --make shellcheck

