#!/bin/sh
# buildsc: Build statically linked ShellCheck
cabal update &&
cabal install --dependencies-only &&
cabal build Paths_ShellCheck &&
ghc -optl-static -optl-pthread -isrc -idist/build/autogen --make shellcheck &&
strip --strip-all shellcheck
